import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  container: { flex: 1, paddingHorizontal: 24, paddingTop: 20, paddingBottom: 40 },
  backBtn: { marginBottom: 32, alignSelf: 'flex-start', padding: 4 },
  backText: { fontSize: 28, color: '#FF6B6B', fontWeight: '300', lineHeight: 32 },
  heading: { fontSize: 26, fontWeight: '700', color: '#111827', marginBottom: 8 },
  sub: { fontSize: 15, color: '#6b7280', marginBottom: 32, lineHeight: 22 },
  label: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8 },
  input: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#111827',
    marginBottom: 24,
  },
  inputError: { borderColor: '#ef4444', backgroundColor: '#fff5f5' },
  errorText: { fontSize: 13, color: '#ef4444', marginTop: -18, marginBottom: 16 },
  button: {
    backgroundColor: '#FF6B6B',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  successContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  successIcon: { fontSize: 52, marginBottom: 20 },
  successHeading: { fontSize: 22, fontWeight: '700', color: '#111827', marginBottom: 10, textAlign: 'center' },
  successSub: { fontSize: 15, color: '#6b7280', textAlign: 'center', lineHeight: 22, marginBottom: 36 },
  backToLogin: { color: '#FF6B6B', fontSize: 15, fontWeight: '600' },
});
